{{- if (.Values.configuration.configMap.create) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
{{- if (.Values.configuration.configMap.files.tarName) }}
  {{- (.Files.Glob (printf "%s" .Values.configuration.configMap.files.tarName)).AsConfig | nindent 2 }}
{{- else }}
  {{- (.Files.Glob (printf "%s" .Values.configuration.configMap.files.pattern)).AsConfig | nindent 2 }}
{{- end }}
{{- end }}