{{- if (.Values.configuration.configMap.create) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- if (.Values.configuration.configMap.files.tarName) }}
binaryData:
  {{ .Values.configuration.configMap.files.tarName }}: {{ .Files.Get .Values.configuration.configMap.files.tarName | b64enc | nindent 4 }}
{{- else }}
data:
  {{- (.Files.Glob (printf "%s" .Values.configuration.configMap.files.pattern)).AsConfig | nindent 2 }}
{{- end }}
{{- end }}
