apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bytewax.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: worker
  clusterIP: None
  selector:
    {{- include "bytewax.selectorLabels" . | nindent 4 }}