apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bytewax.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.api.port }}
    name: api
  selector:
    {{- include "bytewax.selectorLabels" . | nindent 4 }}
{{- if (.Values.configuration.jobMode) }}
    job-name: {{ .Release.Name }}
{{- end }}