apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bytewax.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.api.port }}
    name: api
  selector:
    bytewax.io/dataflow-info: {{ .Release.Name }}
    {{- include "bytewax.selectorLabels" . | nindent 4 }}
